version: "3.8"

services:
  entrypoint:
    image: ghcr.io/alexbidenko/personal-blog/client:latest
    expose:
      - 3000
    networks:
      - server
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  server:
    external:
      name: server
