FROM nginx:alpine

COPY main.conf /etc/nginx/nginx.conf

COPY app.conf /etc/nginx/conf.d.default.conf

RUN touch /var/run/nginx.pid && \
    mkdir -p /var/cache/nginx/ipx && \
    chown -R nginx:nginx /etc/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /usr/share/nginx && \
    chown -R nginx:nginx /var/run/nginx.pid

USER nginx

CMD ["nginx", "-g", "daemon off;"]
